name: Deploy Docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Cache MkDocs and Dependencies
        uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ github.run_id }}
          path: |
            .cache
            site/

      - name: Install MkDocs and Dependencies
        run: |
          pip install -r requirements.txt  # Ensure mkdocs-material is in requirements.txt

      - name: Deploy Documentation
        run: mkdocs gh-deploy --force
